Update of main.py
CIA-Oceanix/4dvarnet-core pull request #18
Opened 2021-05-19 10:20 UTC by rfablet

Update de main.py:
- suppression des éléments non nécessaires (sampling, flagMultiScale,....)
- modif de la préparation des données (probablement à l'origine du mismatch avec/sans litghning des versions précédentes)
- modif du modèle de phi_r
- modif de LitModel: 
(i) notamment log dans test/train/eval et option self.automatic_optimization = True/False
(ii) structure du modèle (doublon m_Grad avec model.m_Grad)
(ii) nveau champ self.x_rec pour stocker les résultats de la fonction test

2021-05-19 11:17 UTC, MMAMAR commented on main.py
> +        elif 1*0:
?

2021-05-19 11:17 UTC, MMAMAR commented on main.py
> +            for pg in opt.param_groups:
Why is this lr update both in optimizer step and training step?

2021-05-19 11:17 UTC, MMAMAR commented on main.py
>      def test_epoch_end(self, outputs):
Why there is no .nc output file here?

2021-05-19 11:52 UTC, quentinf00 requested changes

2021-05-19 11:52 UTC, quentinf00 commented on main.py
> +sys.path.append('../4dvarnet-core')
C'est bizarre que tu es besoin de cette ligne, ... Tu sais pourquoi ?

2021-05-19 11:52 UTC, quentinf00 commented on main.py
> +batch_size      = 10#16#4#4#8#12#8#256#
je serais partant pour que l'on suive les conventions standard d'indentation : https://www.python.org/dev/peps/pep-0008/#whitespace-in-expressions-and-statements

2021-05-19 11:52 UTC, quentinf00 commented on main.py
>  if flagRandomSeed == 0:
Est-ce qu'il y a des moments où l'on a pas envie de fixer la seed ? sinon on peut enlever le if

2021-05-19 11:52 UTC, quentinf00 commented on main.py
> +    genFilename  = 'resInterpSLAwSWOT_Exp3_NewSolver_'+str('%03d'%(W))+'x'+str('%03d'%(W))+'x'+str('%02d'%(dT))
pareil ce nom de fichier je le définirais bien en tête de fichier

2021-05-19 11:52 UTC, quentinf00 commented on main.py
> +    dataTraining  = dataTraining.reshape((dT,W,W,dataTraining.shape[3]*dataTraining.shape[4]))
problème de linting (nombre d'espace etc...)

2021-05-19 11:52 UTC, quentinf00 commented on main.py
> +betaX  = None#42.20436766972647
Tu penses pouvoir mettre les nouvelles valeurs de betaX, betagX ici (comme ça on ne refait pas cette epoch à chaque execution du script) Ou bien y a t-il une raison que je n'ai pas vue qui rend nécéssaire le calcul systématique de ces hyperparamètres ?

2021-05-19 11:52 UTC, quentinf00 commented on main.py
> +#print(f"{(betaX, betagX)=}")
on peut supprimer ce print si on l'a remplacé par celui du dessus

2021-05-19 11:52 UTC, quentinf00 commented on main.py
> +        #self.m_Grad       =
à nettoyer

2021-05-19 11:52 UTC, quentinf00 commented on main.py
> +    #def validation_epoch_end(self, training_step_outputs):
à nettoyer

2021-05-19 11:52 UTC, quentinf00 commented on main.py
> +    def training_epoch_end(self, training_step_outputs):
Pourquoi avoir ajouter ce code qui ne fait rien ?

2021-05-19 11:52 UTC, quentinf00 commented on main.py
> +            if 1:#(batch_idx + 1) % 2 == 0:
enlever if

2021-05-19 11:52 UTC, quentinf00 commented on main.py
> +        if 1*1 :
enlever les if True

2021-05-19 11:52 UTC, quentinf00 commented on main.py
> +        return optimizer
donc tu as enlever les mises à jours des learning rate ?

2021-05-19 11:52 UTC, quentinf00 commented on main.py
> +#model_H = Model_H()
supprimer commentaire

2021-05-19 11:52 UTC, quentinf00 commented on main.py
> +#model_LR = ModelLR()
supprimer commentaire

2021-05-19 12:53 UTC, rfablet commented on main.py
> +class BiLinUnit(torch.nn.Module):
just because i've updated the parameterization of phi. No impact wrt previous version

2021-05-19 12:54 UTC, rfablet commented on main.py
> +            for pg in opt.param_groups:
that's a mistake. When using automatic_optimization = True, this is not called on when using automatic_optimization = False

2021-05-19 12:57 UTC, rfablet commented on main.py
>      def test_epoch_end(self, outputs):
I think it's better to save result file in the main especially if we cannot provide the path of file where to save the results. Now the outputs of the test function is stored in self.x_rec

2021-05-19 13:05 UTC, rfablet commented on main.py
> +sys.path.append('../4dvarnet-core')
oui. Copier/coller du fichier principal que j'utilise dans une autre répertoire, pour ne pas avoir trop de fichiers parasites :) dans ma branche 4dvarnet.

2021-05-19 13:46 UTC, rfablet commented on main.py
>  if flagRandomSeed == 0:
oui ici.

2021-05-19 13:47 UTC, rfablet commented on main.py
> +if os.path.isdir(dirREF) == True :
C'est pour pouvoir utiliser le même code sur lse serveurs imt et jeanzay avec des path différents

2021-05-19 13:59 UTC, rfablet commented on main.py
> +        if 1*1 :
je ne pense pas que l'on va utiliser d'autres optimisers. j'ai essayé qd je n'arrivais pas converger avec lightning...

2021-05-19 14:02 UTC, rfablet commented on main.py
> +        return optimizer
ou avec le scheduler mais j'ai modifié à la "main" les lr dans le training_step. 
pas vu comment générer ave le scheduler le fait de réaugmenter le lr qd on change de nbre d'iters de gradients

2021-05-19 14:38 UTC, rfablet commented on main.py
> +#model_LR = ModelLR()
done

2021-05-19 19:37 UTC, quentinf00 commented on main.py
> +            lrCurrent = self.lrUpdate[indx]
Je pense qu'il faudrait déplacer ça dans on_train_epoch_start peut être pour ne pas le faire à chaque batch

2021-05-19 19:40 UTC, quentinf00 commented on main.py
> +        return optimizer
:+1:

2021-05-19 19:40 UTC, quentinf00 commented on main.py
> +            if (batch_idx + 1) % self.Kbatch == 0:
nom d'attribut en snake case (minuscule avec underscore)

2021-05-20 12:39 UTC, rfablet commented on main.py
> -dataTest = extract_SpaceTimePatches(qHR, ii3, jj3, W, dT, rnd1, rnd2, dx)
not very important now. To be modified after this PR

2021-05-20 12:40 UTC, rfablet commented on main.py
> +            if (batch_idx + 1) % self.Kbatch == 0:
modifiee pour les variables du LitModel

2021-05-20 16:57 UTC, MMAMAR approved these changes

2021-05-20 21:02 UTC, quentinf00 approved these changes

2021-05-20 21:13 UTC, quentinf00 approved these changes

2021-05-20 21:14 UTC, merged