Update of dataloader to load SST data
CIA-Oceanix/4dvarnet-core pull request #33
Opened 2021-05-26 13:57 UTC by rfablet

update of new_dataloading.py to load (optionally) SST data in additon to SSH data
add in the main of "train_with_sst" and "dataloading=with_sst"

2021-05-26 14:02 UTC, rfablet commented
Je n'ai modifié pour l'instant que la partie dataloader et les entrées du modèle LitModelwithSST pour créer le main train_with_sst avec le nouveau dataloader.

2021-05-27 07:19 UTC, quentinf00 requested changes

2021-05-27 07:19 UTC, quentinf00 commented on models.py
> +        targets_OI, inputs_Mask, targets_GT, sst_GT = batch
Est-ce qu'il y a d'autres choses qui changent vis à vis du à part cette ligne ? Sinon tu peux remplacer toute la classe par : 
```
class LitModelwithSST(LitModel):
    def compute_loss(self, batch, phase):
        targets_OI, inputs_Mask, targets_GT, sst_GT = batch
        return super().compute_loss((targets_OI, inputs_Mask, targets_GT), phase)
```

2021-05-27 07:19 UTC, quentinf00 commented on main.py
> +    def run_with_sst(self, ckpt_path=None, dataloader="test", **trainer_kwargs):
Ça fait pas mal de duplication, et d'ailleurs je pense qu'il y a des coquille : est-ce que ça ne devrait pas être `train_with_sst` ?

La manière dont j'aurai implémenter la diff, j'aurais dans le init ajouter un attribut : 
```
def __init__(...)
   ....
   self..lit_cls = LitModelWithSST if dataloading == "with_sst" else LitModel
```
ensuite j'aurais juste changer le get_model : 

```
    def _get_model(self, ckpt_path=None):
	def _get_model(self, ckpt_path=None):
            mod = self.lit_cls(hparam=cfg, w_loss=wLoss, var_Tr=self.var_Tr, var_Tt=self.var_Tt, var_Val=self.var_Val)
        return mod
```

2021-05-27 07:19 UTC, quentinf00 commented on main.py
> +    def run_with_sst(self, ckpt_path=None, dataloader="test", **trainer_kwargs):
Ça permet de ne pas copier coller tous les train, test, run, get_model, profile etc... :)

2021-05-28 07:27 UTC, rfablet commented on models.py
> +        targets_OI, inputs_Mask, targets_GT, sst_GT = batch
Oui pour l'instant, je n'ai modifié que la ligne 400. C'était pour vérifier que cela fonctionnait avec le dataloader sst (sans utiliser la sst). Il y aura une 2ème PR avec la modif du compute_loss. Dans le cas de la SST, il faut modifier l'appel de model( )

2021-05-28 07:32 UTC, rfablet commented on main.py
> +    def run_with_sst(self, ckpt_path=None, dataloader="test", **trainer_kwargs):
oui effectivement. Je vais modifier cela.

2021-05-28 15:21 UTC, closed without merging