First stochastic version
CIA-Oceanix/4dvarnet-core pull request #43
Opened 2021-06-18 09:06 UTC by maxbeauchamp

* add stochastic version of Phi_r (=Phi(x) + alpha(x)*g(W), x: state, W: white noise, alpha and g are basic CNNs)
* deal with the new stochastic version in the LitModel
* add stochastic options in a new config_stochastic.py file -> how to deal with multiple config files in the main ?
* add a new plot_ensemble function in the metrics.py

2021-06-18 12:45 UTC, quentinf00 requested changes

2021-06-18 12:45 UTC, quentinf00 commented on main.py
> -import config
Voilà je pense que ça n'a en effet pas à être plus compliqué que ça, par contre je mettrais bien cet import dans le runner en fonction d'un paramètre que l'on peut passer à la commande

2021-06-18 12:45 UTC, quentinf00 commented on models.py
> +class Correlate_Noise(torch.nn.Module):
On ne mets pas d'underscore dans le nom des classes en python :stuck_out_tongue:

2021-06-18 12:45 UTC, quentinf00 commented on models.py
> +    def __init__(self,ShapeData, Dim_CN):
Et le nom des variable en snake case shape_data, dim_cn

2021-06-18 12:45 UTC, quentinf00 commented on models.py
> +class Regularize_Variance(torch.nn.Module):
Idem sur les convention de casse :)

2021-06-18 12:45 UTC, quentinf00 commented on models.py
> +        if self.hparams.stochastic == True :
Ça pour le coup je pense que c'est le genre de truc pour lesquels on veut faire attention, si on rajoute plusieurs flag comme ça dans le Lightning module, ça peut dégrader un peu la lisibilité du code

2021-06-18 12:45 UTC, quentinf00 commented on models.py
> +            self.x_rec = pred[:,int(self.hparams.dT/2),:,:]
cette ligne là ne sert à rien il me semble (idem que ligne 360)

2021-06-18 13:09 UTC, maxbeauchamp commented on models.py
> +    def __init__(self,ShapeData, Dim_CN):
done

2021-06-18 13:10 UTC, maxbeauchamp commented on models.py
> +class Regularize_Variance(torch.nn.Module):
done

2021-06-18 13:10 UTC, maxbeauchamp commented on models.py
> +    def __init__(self,ShapeData, Dim_CN):
done

2021-06-18 13:10 UTC, maxbeauchamp commented on models.py
> +            self.x_rec = pred[:,int(self.hparams.dT/2),:,:]
l.370 est utilisée dans le cas non stochastique (pas de membres en dimension supplémentaires)

2021-06-18 13:38 UTC, maxbeauchamp commented on main.py
> -import config
ok j'ai ajouté un parmètre pour le config file dans le runner : j'ai en conséquence dû passer certaines variables (comme cfg) en argument de la classe self.cfg, etc.)

2021-06-18 13:42 UTC, maxbeauchamp commented on models.py
> +        if self.hparams.stochastic == True :
effectivement c'est là où on pourrait se demander si on fait plusieurs Lit Model ou pas. De mon côté j'aurai tendance à intégrer cette version stochastique dans le LitModel car ce n'est pas (trop) lourd. Par contre effectivement dès que les données et cas d'application sont différents (SSH seule, SSH/SST/u/v, Lorentz, etc..), il faudra sûrement faire des litmodel dissociés ?

2021-06-18 18:47 UTC, rfablet commented on models.py
> +        if self.hparams.stochastic == True :
Je pense que pour le LitModel ce serait mieux de faire une version spécifique pour un LitModel Stochastique pour garder une version de "base" simple. Même si la modif est assez simple ici au niveau du solver, le modèle stochastique implique quand même des sorties de nature différente (typiquement un ensemble de membre ou une moyenne et une covariance,....). Le calcul de la moyenne peut aussi nécessiter d'ajouter un "petit" modèle spécifique qui détermine une pondération "optimale" des différents poids,.... Comme le modèle stochastique pourra également intégrer un volet sochastique au niveau du solver, on risque d'assez vite vouloir empiler les ajouts.
Il est possible de créer une nouvelle classe LitModel qui hérite de la version de base pour conserver un certaine nbre d'élément commun.

2021-06-21 07:57 UTC, maxbeauchamp commented on models.py
> +        if self.hparams.stochastic == True :
ok ca march je vais m'occuper de ça

2021-06-21 09:07 UTC, maxbeauchamp commented on models.py
> +        if self.hparams.stochastic == True :
modifs faites : ce serait peut-être bien de dissocier dans une autre PR les litmodel dans des fichiers indépendants de models.py, qui selon moi devrait plus contenir les modèles des architectures NN pour les prior et/ou opérateurs d'observation.

2021-06-21 09:14 UTC, quentinf00 commented on lit_model_stochastic.py
> +        if self.hparams.stochastic == True :
Je ne suis pas sur que ces tests soient encore nécéssaire si ?

2021-06-21 09:15 UTC, maxbeauchamp commented on lit_model_stochastic.py
> +        if self.hparams.stochastic == True :
oui tu as raison je remets à jour

2021-06-21 09:18 UTC, quentinf00 approved these changes

2021-06-21 09:19 UTC, merged